# -*- coding: utf-8 -*-
"""
Created on Tue Feb  2 21:29:39 2016

@author: viki
"""

SENSOR_COLOR_DETECT_NONE = -1
SENSOR_COLOR_DETECT_BLACK = 0
SENSOR_COLOR_DETECT_WHITE = 1
SENSOR_COLOR_DETECT_GREEN = 2


SENSOR_COLOR_DETECT_LINE_ID = 1
