# -*- coding: utf-8 -*-
"""
Created on Tue Feb  2 21:29:39 2016

@author: viki
"""

SENSOR_COLOR_DETECT_NONE = -1
SENSOR_COLOR_DETECT_BLACK = 0
SENSOR_COLOR_DETECT_WHITE = 1
SENSOR_COLOR_DETECT_GREEN = 2


SENSOR_COLOR_DETECT_LINE_ID = 1
SENSOR_NOSE_ULTRASONIC_ID = 2

COMMAND_INIT_LEARNING = 1
COMMAND_END_LEARNING = 2
COMMAND_PLAY = 3
COMMAND_STOP = 4
COMMAND_BAD = 5